#!/bin/bash

function pigHelper() {
cat $1 | 
	sed 's/"search",,,"ebay.com",,,//' | 
	sed 's/","/\n/' | 
	sed 's/,"\$/\n/' | 
	sed 's/""\}","/\n/' | 
	grep -v '\/images' | 
	grep -v '^"request_' | 
	grep -v '^request_' | 
	grep -A 1 '^[0-9][0-9],' | 
	sed 's/^[0-9][0-9]/|++|/' | 
	awk '{
		print $0 "@"
	}' | 
	tr -d '\n' | 
	sed 's/--@|++|,"/\n/g' | 
	sed 's/",,,/@/' | 
	sed 's/,@/@/g' | 
	tr '@' '\t';
}
