version: '3.4'

services:
  isit420_ecomcourseproject:
    image: isit420ecomcourseproject:dev
    container_name: ISIT420_eComCourseProject
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ISIT420_eComCourseProject"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/ericsergio/Projects/ISIT420_eComCourseProject/ISIT420_eComCourseProject:/app
      - /Users/ericsergio/Projects/ISIT420_eComCourseProject:/src
      - /Users/ericsergio/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/ericsergio/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/ISIT420_eComCourseProject.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true